<?php $statsHost = ''; ?>
<div class="narrow">

	<div class="bodyContent single">
		<h1>Authorization</h1>



		<div id="result" class="pageMessenger">
		</div>

		<form id="authForm" action="<?php echo htmlspecialchars($statsHost); ?>/auth/index.php" method="post" onsubmit="return false;">
			<table class="nice">
				<thead>
					<tr>
						<th colspan="2">
							Domain successfully authorized
						</th>
					</tr>
				</thead>
				<tr>
					<td width="1%">Your&nbsp;Domain</td>
					<td><input type="text" class="text" name="auth[host]" value="<?php echo htmlspecialchars($_SERVER['HTTP_HOST']); ?>" /></td>
				</tr>
				<tr>
					<td width="1%">Order&nbsp;ID</td>
					<td><input type="text" class="text" name="auth[order_id]" /></td>
				</tr>
				<tr>
					<td>Email</td>
					<td><input type="text" class="text" name="auth[email]" /></td>
				</tr>
				<tr class="controls left">
					<td></td>
					<td>
						<input type="submit" class="button buttonSave" value="Send"/>
					</td>
				</tr>
			</table>
		</form>
	</div>

	<script type="text/javascript">
	  $(document).ready(function() {
	      $.cookie('authCheck', "good");
	    $('#authForm').submit(function () {
	        $('#result').html('');
                  $('#result')[0].innerHTML += '<div class="message">Domain successfully authorized</div>';
	      });
	  });
	</script>
</div>
